### ISSUE TITLE
Resistance not displaying on possibly non-calibrated bike

### ISSUE THREAD

**Issue by tokitoppers** [benwithjamin/Derailleur#1]
Hi thank you for this app.  Flywheel cancelled the service before I even had a chance to download the app and calibrate my bike.  I downloaded the App to my MacBook successful but I’m having trouble with locating the Bluetooth on my bike(which didn’t come with the touchscreen). I have the bike plugged in and tried pedaling.  Is there any way to verify that the Bluetooth is on?

**Comment by benwithjamin** [comment]
Hi there, it should turn on if you start pedaling. My app doesn’t really come with any error handling unfortunately so I’d check the basics like Bluetooth being turned on on the MacBook etc. If you still have trouble I can see about adding some error messages and we can troubleshoot that way!

Update: I'll do a quick release that adds some logging so you can see what types of Bluetooth device are around you. We should be able to figure it out!

**Comment by benwithjamin** [comment]
Oh, actually, you might be able to test the Bluetooth by using an app on your phone - there's an app called LightBlue on iPhone. Basically you should look to see if there's a device with "Flywheel" in the name. If there isn't, it might be a battery issue on your bike - it actually uses the large (D, I think) batteries in a compartment by your left foot if you're sat on the saddle. Let me know how you get on!

**Comment by tokitoppers** [comment]
Oh wow that was it!  I completely forgot that my box came with batteries
and I had thrown it aside.  I got it working but its only showing the
cadence and not the resistance.  (It just stays at zero).  Do you have any
suggestions for this?  Thanks again this is such a game changer!

**Comment by benwithjamin** [comment]
That's great! I wonder if it needs to be calibrated - I had assumed that calibration was a Flywheel term because the bike spits out a value between 0 and 100, and since Flywheel's Torq used to be 0 to 60 (IIRC) I thought that was their "calibration" mapping the values. Let me have a look and see what I can find out.

**Comment by benwithjamin** [comment]
Okay, in the latest version, if your bike sends a message saying it needs to be calibrated, the app will say so in the status bar. If that happens, let me know and we can try to figure out how to calibrate it!

**Comment by tokitoppers** [comment]
Hi just tried version 3.  I’m not getting any message for calibration (attached an image). Is the status bar the bottom where it says “connected to your flywheel bike”?

**Comment by benwithjamin** [comment]
Interesting... I've put together a debug release where you can click on the bike menu and then click Enable debug mode. This'll ask you for somewhere to save a log file. It will only log the data sent by your bike but it will enable me to try to figure out what is happening.

If you can send it here on GitHub (your attachment didn't work) that would be great. I'll be able to take another look.

[debug.zip](https://github.com/benwithjamin/Derailleur/files/4626284/debug.zip)

**Comment by tokitoppers** [comment]
![IMG_8646](https://user-images.githubusercontent.com/65276534/81898865-856f2a00-9587-11ea-994d-4afce5ec33cc.jpg)

**Comment by tokitoppers** [comment]
I downloaded the debug version but cannot seem to get any other screen or clickable bike menu.

**Comment by benwithjamin** [comment]
You should see this.

![image](https://user-images.githubusercontent.com/5489784/81899069-d7f01c80-956e-11ea-9c3b-996217114fb1.png)

**Comment by tokitoppers** [comment]
[derailleur.log](https://github.com/benwithjamin/Derailleur/files/4626382/derailleur.log)

**Comment by benwithjamin** [comment]
Thanks for sending that. I'm seeing cadence and workout time (which currently doesn't show on my app but I can add that pretty easily), but not resistance - I take it you tried changing the dial up and down?

I will work on a calibration feature as that's probably the problem.

**Comment by tokitoppers** [comment]
Yes, I did move the resistance dial.  On a side note, I've noticed that moving the dial from 6 to 12 o clock position I get a nice gradual resistance, but from 12 o clock on, the resistance gets increasingly harder with less turns of the dial.  Would that be a calibration issue?

**Comment by benwithjamin** [comment]
Interesting... that's definitely a mechanical issue with the bike rather than a calibration issue. From what I understand, calibration is purely software understanding what the hardware is saying.

**Comment by benwithjamin** [comment]
Hi there, sorry it took me so long - I have had a go at letting you configure the bike via the app. It's pretty basic for now, and I don't have a way to test it, so let me know if it works.

1. Open this version of Derailleur
2. Wait for it to connect to your bike, and it should now say that the bike needs calibration
3. Turn the resistance dial all the way to the left (anticlockwise), then go to the system menu where the debug mode option is and you'll see the option to Calibrate Brake Minimum and Maximum. Click calibrate brake minimum.
4. Turn the resistance dial all the way to the right (clockwise), then do the same, but hit the Maximum button instead.

Hopefully, this will work - you may have to restart the app. As I said, I don't have an uncalibrated bike to test with. If you could turn on debug mode and send me the output if there are any errors, or it continues not to work, that'd be great.
[Derailleur.zip](https://github.com/benwithjamin/Derailleur/files/4686043/Derailleur.zip)

**Comment by tokitoppers** [comment]
Wow it works thank you SO much.  I actually just got my Peloton so now I
can have friends join me on rides and still keep within the metrics.  This
is amazing!

**Comment by milelona** [comment]
Hi, I was wondering if you have any solution for those of us with older macs? I can only get my 2010 Mac up to Os 10.13.6 and not the 10.15 needed.

**Comment by soupy098** [comment]
> Hi there, sorry it took me so long - I have had a go at letting you configure the bike via the app. It's pretty basic for now, and I don't have a way to test it, so let me know if it works.
> 
> 1. Open this version of Derailleur
> 2. Wait for it to connect to your bike, and it should now say that the bike needs calibration
> 3. Turn the resistance dial all the way to the left (anticlockwise), then go to the system menu where the debug mode option is and you'll see the option to Calibrate Brake Minimum and Maximum. Click calibrate brake minimum.
> 4. Turn the resistance dial all the way to the right (clockwise), then do the same, but hit the Maximum button instead.
> 
> Hopefully, this will work - you may have to restart the app. As I said, I don't have an uncalibrated bike to test with. If you could turn on debug mode and send me the output if there are any errors, or it continues not to work, that'd be great.
> [Derailleur.zip](https://github.com/benwithjamin/Derailleur/files/4686043/Derailleur.zip)

I am not able to download it because it's saying its a virus I am on a MacBook air 2016

**Comment by benwithjamin** [comment]
Please read the FAQs.

**Comment by cagnulein** [comment]
@benwithjamin is the source code aligned with this version? I can't find any trace of the calibration process. Am I missing something?

**Comment by mikalasf** [comment]
I'm having the same problem with it not opening. I am not Mac literate. I saved the file and then tried to open it, so not sure how I modified the open close state. Then I saved the zip file to the desktop and when I double click on it, nothing happens.

**Comment by mikalasf** [comment]
I managed to unzip it but then got a message that it closed unexpectedly. This is the error log.
Process:               Derailleur [985]
Path:                  /private/var/folders/*/Derailleur 4.app/Contents/MacOS/Derailleur
Identifier:            com.benwithjamin.derailleur
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Derailleur [985]
User ID:               501

Date/Time:             2021-01-19 09:44:24.705 -0800
OS Version:            Mac OS X 10.15.7 (19H2)
Report Version:        12
Anonymous UUID:        9A515DB4-E5B9-0759-6835-48B28BDF8526


Time Awake Since Boot: 2400 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010dc4c000-000000010dc54000 [   32K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000116d08000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee1fb3b30
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000116d08000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10dc4c000 -        0x10dc53fff +??? (0) <59D468CF-29CF-376E-B3F5-BFC2454A602E> (null)
       0x116d07000 -        0x116d98f47 +??? (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> (null)

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1248
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=864K resident=0K(0%) swapped_out_or_unallocated=864K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             228K        3 
__DATA_CONST                        24K        2 
__LINKEDIT                         248K        2 
__TEXT                             616K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             65.1M       13 

Model: iMac16,2, BootROM 236.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 3.1 GHz, 8 GB, SMC 2.32f21
Graphics: kHW_IntelIrisPro6200Item, Intel Iris Pro Graphics 6200, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346202020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x156), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.2)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE HDD HTS541010A9E662, 1 TB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: 2.4G Wireless Device
Thunderbolt Bus: iMac, Apple Inc., 27.4
